import { Octokit } from '@octokit/rest'
import * as fs from 'fs'
import * as path from 'path'

export interface CommentOptions {
  owner: string
  repo: string
  prNumber: number
  videoPath: string
  githubToken?: string
}

const COMMENT_MARKER = '<!-- git-pr-video -->'

export async function postVideoComment(options: CommentOptions): Promise<string> {
  const octokit = new Octokit({
    auth: options.githubToken || process.env.GITHUB_TOKEN,
  })

  const videoUrl = await uploadToRelease(octokit, options)

  const commentBody = `${COMMENT_MARKER}
## 🎬 PR Demo Video

https://github.com/user-attachments/assets/${path.basename(videoUrl)}

<details>
<summary>Video not loading?</summary>

[Direct link to video](${videoUrl})

</details>

---
*Generated by [git-pr-video](https://github.com/your-username/git-pr-video)*`

  const existingComment = await findExistingComment(octokit, options)

  if (existingComment) {
    await octokit.issues.updateComment({
      owner: options.owner,
      repo: options.repo,
      comment_id: existingComment.id,
      body: commentBody,
    })
    return existingComment.html_url
  }

  const { data: comment } = await octokit.issues.createComment({
    owner: options.owner,
    repo: options.repo,
    issue_number: options.prNumber,
    body: commentBody,
  })

  return comment.html_url
}

async function findExistingComment(
  octokit: Octokit,
  options: CommentOptions
): Promise<{ id: number; html_url: string } | null> {
  const { data: comments } = await octokit.issues.listComments({
    owner: options.owner,
    repo: options.repo,
    issue_number: options.prNumber,
    per_page: 100,
  })

  const existing = comments.find((c) => c.body?.includes(COMMENT_MARKER))
  return existing ? { id: existing.id, html_url: existing.html_url } : null
}

async function uploadToRelease(
  octokit: Octokit,
  options: CommentOptions
): Promise<string> {
  const releaseTag = 'pr-videos'
  const fileName = `pr-${options.prNumber}-${Date.now()}.mp4`

  let release: { id: number; upload_url: string }

  try {
    const { data } = await octokit.repos.getReleaseByTag({
      owner: options.owner,
      repo: options.repo,
      tag: releaseTag,
    })
    release = data
  } catch {
    const { data } = await octokit.repos.createRelease({
      owner: options.owner,
      repo: options.repo,
      tag_name: releaseTag,
      name: 'PR Demo Videos',
      body: 'Auto-generated PR demo videos',
      draft: false,
      prerelease: true,
    })
    release = data
  }

  const videoContent = fs.readFileSync(options.videoPath)

  const { data: asset } = await octokit.repos.uploadReleaseAsset({
    owner: options.owner,
    repo: options.repo,
    release_id: release.id,
    name: fileName,
    data: videoContent as unknown as string,
    headers: {
      'content-type': 'video/mp4',
      'content-length': videoContent.length,
    },
  })

  return asset.browser_download_url
}
